insert into feedback (id_feedback, comment , rating, id_client) values (1, 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi', 1, 1);
insert into feedback (id_feedback, comment , rating, id_client) values (2, 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', 2, 2);
insert into feedback (id_feedback, comment , rating, id_client) values (3, 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 3, 3);
insert into feedback (id_feedback, comment , rating, id_client) values (4, 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 4, 4);
insert into feedback (id_feedback, comment , rating, id_client) values (5, 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 5, 5);
insert into feedback (id_feedback, comment , rating, id_client) values (6, 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium', 6, 6);
insert into feedback (id_feedback, comment , rating, id_client) values (7, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo', 7, 7);
insert into feedback (id_feedback, comment , rating, id_client) values (8, 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 8, 8);
insert into feedback (id_feedback, comment , rating, id_client) values (9, 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula', 9, 9);
insert into feedback (id_feedback, comment , rating, id_client) values (10, 'odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 10, 10);
insert into feedback (id_feedback, comment , rating, id_client) values (11, 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et', 11, 11);
insert into feedback (id_feedback, comment , rating, id_client) values (12, 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', 12, 12);
insert into feedback (id_feedback, comment , rating, id_client) values (13, 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 13, 13);
insert into feedback (id_feedback, comment , rating, id_client) values (14, 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', 14, 14);
insert into feedback (id_feedback, comment , rating, id_client) values (15, 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 15, 15);
insert into feedback (id_feedback, comment , rating, id_client) values (16, 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero', 16, 16);
insert into feedback (id_feedback, comment , rating, id_client) values (17, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat', 17, 17);
insert into feedback (id_feedback, comment , rating, id_client) values (18, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper', 18, 18);
insert into feedback (id_feedback, comment , rating, id_client) values (19, 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam', 19, 19);
insert into feedback (id_feedback, comment , rating, id_client) values (20, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 20, 20);
insert into feedback (id_feedback, comment , rating, id_client) values (21, 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 21, 21);
insert into feedback (id_feedback, comment , rating, id_client) values (22, 'eu massa donec dapibus duis at velit eu est congue elementum in hac', 22, 22);
insert into feedback (id_feedback, comment , rating, id_client) values (23, 'donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio', 23, 23);
insert into feedback (id_feedback, comment , rating, id_client) values (24, 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 24, 24);
insert into feedback (id_feedback, comment , rating, id_client) values (25, 'rhoncus dui vel sem sed sagittis nam congue risus semper porta', 25, 25);
insert into feedback (id_feedback, comment , rating, id_client) values (26, 'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 26, 26);
insert into feedback (id_feedback, comment , rating, id_client) values (27, 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac', 27, 27);
insert into feedback (id_feedback, comment , rating, id_client) values (28, 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et', 28, 28);
insert into feedback (id_feedback, comment , rating, id_client) values (29, 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum', 29, 29);
insert into feedback (id_feedback, comment , rating, id_client) values (30, 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 30, 30);
insert into feedback (id_feedback, comment , rating, id_client) values (31, 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis', 31, 31);
insert into feedback (id_feedback, comment , rating, id_client) values (32, 'suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis', 32, 32);
insert into feedback (id_feedback, comment , rating, id_client) values (33, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 33, 33);
insert into feedback (id_feedback, comment , rating, id_client) values (34, 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean', 34, 34);
insert into feedback (id_feedback, comment , rating, id_client) values (35, 'tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', 35, 35);
insert into feedback (id_feedback, comment , rating, id_client) values (36, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', 36, 36);
insert into feedback (id_feedback, comment , rating, id_client) values (37, 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis', 37, 37);
insert into feedback (id_feedback, comment , rating, id_client) values (38, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', 38, 38);
insert into feedback (id_feedback, comment , rating, id_client) values (39, 'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing', 39, 39);
insert into feedback (id_feedback, comment , rating, id_client) values (40, 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et', 40, 40);
insert into feedback (id_feedback, comment , rating, id_client) values (41, 'ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc', 41, 41);
insert into feedback (id_feedback, comment , rating, id_client) values (42, 'cras in purus eu magna vulputate luctus cum sociis natoque', 42, 42);
insert into feedback (id_feedback, comment , rating, id_client) values (43, 'etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus', 43, 43);
insert into feedback (id_feedback, comment , rating, id_client) values (44, 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 44, 44);
insert into feedback (id_feedback, comment , rating, id_client) values (45, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem', 45, 45);
insert into feedback (id_feedback, comment , rating, id_client) values (46, 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac', 46, 46);
insert into feedback (id_feedback, comment , rating, id_client) values (47, 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est', 47, 47);
insert into feedback (id_feedback, comment , rating, id_client) values (48, 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula', 48, 48);
insert into feedback (id_feedback, comment , rating, id_client) values (49, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis', 49, 49);
insert into feedback (id_feedback, comment , rating, id_client) values (50, 'a libero nam dui proin leo odio porttitor id consequat in consequat ut', 50, 50);
insert into feedback (id_feedback, comment , rating, id_client) values (51, 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 51, 51);
insert into feedback (id_feedback, comment , rating, id_client) values (52, 'nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', 52, 52);
insert into feedback (id_feedback, comment , rating, id_client) values (53, 'in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', 53, 53);
insert into feedback (id_feedback, comment , rating, id_client) values (54, 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', 54, 54);
insert into feedback (id_feedback, comment , rating, id_client) values (55, 'porttitor pede justo eu massa donec dapibus duis at velit eu est', 55, 55);
insert into feedback (id_feedback, comment , rating, id_client) values (56, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', 56, 56);
insert into feedback (id_feedback, comment , rating, id_client) values (57, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat', 57, 57);
insert into feedback (id_feedback, comment , rating, id_client) values (58, 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque', 58, 58);
insert into feedback (id_feedback, comment , rating, id_client) values (59, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', 59, 59);
insert into feedback (id_feedback, comment , rating, id_client) values (60, 'felis donec semper sapien a libero nam dui proin leo odio porttitor', 60, 60);
insert into feedback (id_feedback, comment , rating, id_client) values (61, 'suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce', 61, 61);
insert into feedback (id_feedback, comment , rating, id_client) values (62, 'varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis', 62, 62);
insert into feedback (id_feedback, comment , rating, id_client) values (63, 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 63, 63);
insert into feedback (id_feedback, comment , rating, id_client) values (64, 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget', 64, 64);
insert into feedback (id_feedback, comment , rating, id_client) values (65, 'ante ipsum primis in faucibus orci luctus et ultrices posuere', 65, 65);
insert into feedback (id_feedback, comment , rating, id_client) values (66, 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non', 66, 66);
insert into feedback (id_feedback, comment , rating, id_client) values (67, 'donec semper sapien a libero nam dui proin leo odio porttitor id', 67, 67);
insert into feedback (id_feedback, comment , rating, id_client) values (68, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', 68, 68);
insert into feedback (id_feedback, comment , rating, id_client) values (69, 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis', 69, 69);
insert into feedback (id_feedback, comment , rating, id_client) values (70, 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', 70, 70);
insert into feedback (id_feedback, comment , rating, id_client) values (71, 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', 71, 71);
insert into feedback (id_feedback, comment , rating, id_client) values (72, 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis', 72, 72);
insert into feedback (id_feedback, comment , rating, id_client) values (73, 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 73, 73);
insert into feedback (id_feedback, comment , rating, id_client) values (74, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 74, 74);
insert into feedback (id_feedback, comment , rating, id_client) values (75, 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', 75, 75);
insert into feedback (id_feedback, comment , rating, id_client) values (76, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', 76, 76);
insert into feedback (id_feedback, comment , rating, id_client) values (77, 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget', 77, 77);
insert into feedback (id_feedback, comment , rating, id_client) values (78, 'convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut', 78, 78);
insert into feedback (id_feedback, comment , rating, id_client) values (79, 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis', 79, 79);
insert into feedback (id_feedback, comment , rating, id_client) values (80, 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor', 80, 80);
insert into feedback (id_feedback, comment , rating, id_client) values (81, 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', 81, 81);
insert into feedback (id_feedback, comment , rating, id_client) values (82, 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 82, 82);
insert into feedback (id_feedback, comment , rating, id_client) values (83, 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 83, 83);
insert into feedback (id_feedback, comment , rating, id_client) values (84, 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed', 84, 84);
insert into feedback (id_feedback, comment , rating, id_client) values (85, 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia', 85, 85);
insert into feedback (id_feedback, comment , rating, id_client) values (86, 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu', 86, 86);
insert into feedback (id_feedback, comment , rating, id_client) values (87, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 87, 87);
insert into feedback (id_feedback, comment , rating, id_client) values (88, 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 88, 88);
insert into feedback (id_feedback, comment , rating, id_client) values (89, 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', 89, 89);
insert into feedback (id_feedback, comment , rating, id_client) values (90, 'habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', 90, 90);
insert into feedback (id_feedback, comment , rating, id_client) values (91, 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', 91, 91);
insert into feedback (id_feedback, comment , rating, id_client) values (92, 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 92, 92);
insert into feedback (id_feedback, comment , rating, id_client) values (93, 'ut erat curabitur gravida nisi at nibh in hac habitasse', 93, 93);
insert into feedback (id_feedback, comment , rating, id_client) values (94, 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', 94, 94);
insert into feedback (id_feedback, comment , rating, id_client) values (95, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 95, 95);
insert into feedback (id_feedback, comment , rating, id_client) values (96, 'nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam', 96, 96);
insert into feedback (id_feedback, comment , rating, id_client) values (97, 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum', 97, 97);
insert into feedback (id_feedback, comment , rating, id_client) values (98, 'rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis', 98, 98);
insert into feedback (id_feedback, comment , rating, id_client) values (99, 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', 99, 99);
insert into feedback (id_feedback, comment , rating, id_client) values (100, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 100, 100);
