insert into hotel (hotel_name, address, id_province) values ('Akory hotel Diégo', "Apt 1009", 5);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Antsirabe', '17th Floor', 7);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Tuléar', 'PO Box 72484', 9);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Fianarantsoa', '10th Floor', 3);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Majunga', 'PO Box 10698', 6);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Morondava', 'Apt 1099', 1);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Diégo', "Apt 1009", 5);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Antsirabe', '17th Floor', 7);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Tuléar', 'PO Box 72484', 9);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Fianarantsoa', '10th Floor', 3);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Majunga', 'PO Box 10698', 6);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Morondava', 'Apt 1099', 1);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Diégo', "Apt 1009", 5);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Antsirabe', '17th Floor', 7);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Tuléar', 'PO Box 72484', 9);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Fianarantsoa', '10th Floor', 3);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Majunga', 'PO Box 10698', 6);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Morondava', 'Apt 1099', 1);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Diégo', "Apt 1009", 5);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Antsirabe', '17th Floor', 7);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Tuléar', 'PO Box 72484', 9);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Fianarantsoa', '10th Floor', 3);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Majunga', 'PO Box 10698', 6);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Morondava', 'Apt 1099', 1);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Diégo', "Apt 1009", 5);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Antsirabe', '17th Floor', 7);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Tuléar', 'PO Box 72484', 9);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Fianarantsoa', '10th Floor', 3);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Majunga', 'PO Box 10698', 6);
insert into hotel (hotel_name, address, id_province) values ('Akory hotel Morondava', 'Apt 1099', 1);