insert into hotel (id_hotel, hotel_name, address, id_province) values (1, 'McDermott, Braun and Thompson', '51830 Arizona Pass', 1);
insert into hotel (id_hotel, hotel_name, address, id_province) values (2, 'Gleichner-Padberg', '44015 Crest Line Trail', 2);
insert into hotel (id_hotel, hotel_name, address, id_province) values (3, 'McKenzie, Marquardt and Jenkins', '80 Burning Wood Park', 3);
insert into hotel (id_hotel, hotel_name, address, id_province) values (4, 'Stark, Keeling and Prohaska', '3 Little Fleur Drive', 4);
insert into hotel (id_hotel, hotel_name, address, id_province) values (5, 'Oberbrunner LLC', '08326 Banding Drive', 5);
insert into hotel (id_hotel, hotel_name, address, id_province) values (6, 'Russel, Spinka and Jenkins', '7 Burning Wood Pass', 6);
insert into hotel (id_hotel, hotel_name, address, id_province) values (7, 'Littel-Ryan', '7 Acker Plaza', 7);
insert into hotel (id_hotel, hotel_name, address, id_province) values (8, 'Koelpin-Hettinger', '763 Valley Edge Drive', 8);
insert into hotel (id_hotel, hotel_name, address, id_province) values (9, 'Mraz-Cormier', '3061 Bultman Crossing', 9);
insert into hotel (id_hotel, hotel_name, address, id_province) values (10, 'Cummings Inc', '88 Lillian Hill', 10);
insert into hotel (id_hotel, hotel_name, address, id_province) values (11, 'Swaniawski, Greenfelder and Wyman', '47 Union Point', 11);
insert into hotel (id_hotel, hotel_name, address, id_province) values (12, 'Halvorson-Jones', '384 Scofield Pass', 12);
insert into hotel (id_hotel, hotel_name, address, id_province) values (13, 'Ondricka and Sons', '27851 Nova Terrace', 13);
insert into hotel (id_hotel, hotel_name, address, id_province) values (14, 'Bruen LLC', '04 Prairie Rose Alley', 14);
insert into hotel (id_hotel, hotel_name, address, id_province) values (15, 'Swift-Huels', '1364 Katie Way', 15);
insert into hotel (id_hotel, hotel_name, address, id_province) values (16, 'Gottlieb and Sons', '74 Warbler Point', 16);
insert into hotel (id_hotel, hotel_name, address, id_province) values (17, 'Schimmel and Sons', '52498 Harper Crossing', 17);
insert into hotel (id_hotel, hotel_name, address, id_province) values (18, 'Gleason, Howe and Carter', '07 Merchant Center', 18);
insert into hotel (id_hotel, hotel_name, address, id_province) values (19, 'Hegmann-Huel', '9 Bartillon Way', 19);
insert into hotel (id_hotel, hotel_name, address, id_province) values (20, 'Gibson, West and Luettgen', '6 Blue Bill Park Trail', 20);
insert into hotel (id_hotel, hotel_name, address, id_province) values (21, 'Osinski, Sporer and Weissnat', '18 Fallview Terrace', 21);
insert into hotel (id_hotel, hotel_name, address, id_province) values (22, 'Rogahn LLC', '5107 Ohio Place', 22);
insert into hotel (id_hotel, hotel_name, address, id_province) values (23, 'Bernier, Schamberger and Bradtke', '22 Mayfield Street', 23);
insert into hotel (id_hotel, hotel_name, address, id_province) values (24, 'Shields-Metz', '601 Nobel Park', 24);
insert into hotel (id_hotel, hotel_name, address, id_province) values (25, 'Fahey-Haley', '98 Warbler Trail', 25);
insert into hotel (id_hotel, hotel_name, address, id_province) values (26, 'Zemlak-D''Amore', '4 Lighthouse Bay Trail', 26);
insert into hotel (id_hotel, hotel_name, address, id_province) values (27, 'Ebert, Purdy and Sawayn', '2 Hintze Alley', 27);
insert into hotel (id_hotel, hotel_name, address, id_province) values (28, 'Raynor Group', '50 Warrior Lane', 28);
insert into hotel (id_hotel, hotel_name, address, id_province) values (29, 'Wilkinson and Sons', '79332 Holy Cross Avenue', 29);
insert into hotel (id_hotel, hotel_name, address, id_province) values (30, 'Fadel LLC', '0631 Oneill Plaza', 30);
insert into hotel (id_hotel, hotel_name, address, id_province) values (31, 'Parisian-Goodwin', '15 Blackbird Drive', 31);
insert into hotel (id_hotel, hotel_name, address, id_province) values (32, 'Littel-Bashirian', '00 Kings Place', 32);
insert into hotel (id_hotel, hotel_name, address, id_province) values (33, 'Quigley, Gerlach and Mertz', '80 Lukken Junction', 33);
insert into hotel (id_hotel, hotel_name, address, id_province) values (34, 'Gerlach-Gottlieb', '229 Larry Pass', 34);
insert into hotel (id_hotel, hotel_name, address, id_province) values (35, 'Adams, Kutch and Greenholt', '0 North Park', 35);
insert into hotel (id_hotel, hotel_name, address, id_province) values (36, 'Willms, Klein and Abbott', '340 New Castle Court', 36);
insert into hotel (id_hotel, hotel_name, address, id_province) values (37, 'Schultz and Sons', '5 Crownhardt Parkway', 37);
insert into hotel (id_hotel, hotel_name, address, id_province) values (38, 'Lowe-Homenick', '9 Gale Alley', 38);
insert into hotel (id_hotel, hotel_name, address, id_province) values (39, 'Pagac-Yost', '78012 Paget Parkway', 39);
insert into hotel (id_hotel, hotel_name, address, id_province) values (40, 'Pagac, Ondricka and Heaney', '6121 Shelley Hill', 40);
insert into hotel (id_hotel, hotel_name, address, id_province) values (41, 'Grady, Graham and Jacobson', '869 Kipling Place', 41);
insert into hotel (id_hotel, hotel_name, address, id_province) values (42, 'Romaguera and Sons', '75109 Riverside Drive', 42);
insert into hotel (id_hotel, hotel_name, address, id_province) values (43, 'Buckridge, Hyatt and MacGyver', '3 Buena Vista Pass', 43);
insert into hotel (id_hotel, hotel_name, address, id_province) values (44, 'Douglas Group', '79 Clyde Gallagher Alley', 44);
insert into hotel (id_hotel, hotel_name, address, id_province) values (45, 'Botsford-Kirlin', '0833 Center Place', 45);
insert into hotel (id_hotel, hotel_name, address, id_province) values (46, 'Schroeder, Cronin and Herzog', '27 Stuart Park', 46);
insert into hotel (id_hotel, hotel_name, address, id_province) values (47, 'Mann, Schmeler and Haag', '57 Sachs Court', 47);
insert into hotel (id_hotel, hotel_name, address, id_province) values (48, 'Simonis, Fadel and Cummings', '5689 Onsgard Hill', 48);
insert into hotel (id_hotel, hotel_name, address, id_province) values (49, 'Douglas-Dickens', '8724 Thierer Road', 49);
insert into hotel (id_hotel, hotel_name, address, id_province) values (50, 'Wuckert, Wilderman and Thiel', '0158 Elgar Circle', 50);
insert into hotel (id_hotel, hotel_name, address, id_province) values (51, 'Kuhn, Batz and O''Conner', '59599 4th Hill', 51);
insert into hotel (id_hotel, hotel_name, address, id_province) values (52, 'Franecki, Marquardt and Hand', '3274 Maple Terrace', 52);
insert into hotel (id_hotel, hotel_name, address, id_province) values (53, 'Emard-Johnston', '29 Holy Cross Street', 53);
insert into hotel (id_hotel, hotel_name, address, id_province) values (54, 'Torp-McDermott', '53509 Golf Street', 54);
insert into hotel (id_hotel, hotel_name, address, id_province) values (55, 'Armstrong, Runolfsdottir and Durgan', '02929 Sunnyside Plaza', 55);
insert into hotel (id_hotel, hotel_name, address, id_province) values (56, 'Runolfsson, Terry and Turcotte', '291 Macpherson Point', 56);
insert into hotel (id_hotel, hotel_name, address, id_province) values (57, 'Satterfield-Collins', '40206 Oriole Center', 57);
insert into hotel (id_hotel, hotel_name, address, id_province) values (58, 'Bednar-DuBuque', '1473 Hallows Lane', 58);
insert into hotel (id_hotel, hotel_name, address, id_province) values (59, 'Stracke LLC', '58502 Butternut Road', 59);
insert into hotel (id_hotel, hotel_name, address, id_province) values (60, 'Barrows, Wiza and Heidenreich', '8583 Menomonie Terrace', 60);
insert into hotel (id_hotel, hotel_name, address, id_province) values (61, 'Stanton Group', '2 Canary Street', 61);
insert into hotel (id_hotel, hotel_name, address, id_province) values (62, 'Durgan, Gutmann and Toy', '07 North Court', 62);
insert into hotel (id_hotel, hotel_name, address, id_province) values (63, 'Marks, Boyle and Robel', '81 Mitchell Point', 63);
insert into hotel (id_hotel, hotel_name, address, id_province) values (64, 'Jerde and Sons', '4543 Maple Terrace', 64);
insert into hotel (id_hotel, hotel_name, address, id_province) values (65, 'Runte LLC', '66 Katie Park', 65);
insert into hotel (id_hotel, hotel_name, address, id_province) values (66, 'Gleason-Hamill', '477 Green Point', 66);
insert into hotel (id_hotel, hotel_name, address, id_province) values (67, 'Lemke-Kessler', '4 Stone Corner Drive', 67);
insert into hotel (id_hotel, hotel_name, address, id_province) values (68, 'Metz-Rodriguez', '201 Bunting Road', 68);
insert into hotel (id_hotel, hotel_name, address, id_province) values (69, 'Ziemann and Sons', '133 Reinke Plaza', 69);
insert into hotel (id_hotel, hotel_name, address, id_province) values (70, 'Parisian, Erdman and Osinski', '6 Division Place', 70);
insert into hotel (id_hotel, hotel_name, address, id_province) values (71, 'Labadie, Batz and Mayer', '47 Melvin Crossing', 71);
insert into hotel (id_hotel, hotel_name, address, id_province) values (72, 'Connelly-Murphy', '11 Pleasure Lane', 72);
insert into hotel (id_hotel, hotel_name, address, id_province) values (73, 'Cummings-Mohr', '514 Mcbride Point', 73);
insert into hotel (id_hotel, hotel_name, address, id_province) values (74, 'Dietrich-Schuppe', '10942 Stang Drive', 74);
insert into hotel (id_hotel, hotel_name, address, id_province) values (75, 'Schmidt-Hilll', '2746 Mendota Center', 75);
insert into hotel (id_hotel, hotel_name, address, id_province) values (76, 'Considine-Goldner', '1002 Westend Pass', 76);
insert into hotel (id_hotel, hotel_name, address, id_province) values (77, 'Sporer-Wisoky', '8171 Stuart Lane', 77);
insert into hotel (id_hotel, hotel_name, address, id_province) values (78, 'Kiehn, Stroman and Koelpin', '4 Westerfield Lane', 78);
insert into hotel (id_hotel, hotel_name, address, id_province) values (79, 'Ondricka LLC', '0 Bayside Drive', 79);
insert into hotel (id_hotel, hotel_name, address, id_province) values (80, 'Homenick and Sons', '589 Rieder Avenue', 80);
insert into hotel (id_hotel, hotel_name, address, id_province) values (81, 'Gerlach-Frami', '4 Utah Park', 81);
insert into hotel (id_hotel, hotel_name, address, id_province) values (82, 'Tillman and Sons', '012 Darwin Drive', 82);
insert into hotel (id_hotel, hotel_name, address, id_province) values (83, 'Mitchell-Thompson', '5993 West Parkway', 83);
insert into hotel (id_hotel, hotel_name, address, id_province) values (84, 'Rau Group', '3 Bartelt Center', 84);
insert into hotel (id_hotel, hotel_name, address, id_province) values (85, 'Heathcote LLC', '17 Daystar Center', 85);
insert into hotel (id_hotel, hotel_name, address, id_province) values (86, 'Little-Runolfsson', '210 Lukken Center', 86);
insert into hotel (id_hotel, hotel_name, address, id_province) values (87, 'Herzog-Murray', '082 Colorado Way', 87);
insert into hotel (id_hotel, hotel_name, address, id_province) values (88, 'Erdman and Sons', '5609 American Ash Way', 88);
insert into hotel (id_hotel, hotel_name, address, id_province) values (89, 'Powlowski-Metz', '9270 Forest Run Circle', 89);
insert into hotel (id_hotel, hotel_name, address, id_province) values (90, 'Morar-Cruickshank', '56 Del Mar Lane', 90);
insert into hotel (id_hotel, hotel_name, address, id_province) values (91, 'Stamm, Beer and Carroll', '7 Stang Junction', 91);
insert into hotel (id_hotel, hotel_name, address, id_province) values (92, 'Hoeger Inc', '0 North Place', 92);
insert into hotel (id_hotel, hotel_name, address, id_province) values (93, 'Crist Group', '8 Forest Park', 93);
insert into hotel (id_hotel, hotel_name, address, id_province) values (94, 'Smith-Boehm', '17156 Rigney Terrace', 94);
insert into hotel (id_hotel, hotel_name, address, id_province) values (95, 'Terry and Sons', '467 Drewry Hill', 95);
insert into hotel (id_hotel, hotel_name, address, id_province) values (96, 'Hirthe-Reichel', '77 Fairview Point', 96);
insert into hotel (id_hotel, hotel_name, address, id_province) values (97, 'Hyatt, Tromp and Hagenes', '31 Schurz Junction', 97);
insert into hotel (id_hotel, hotel_name, address, id_province) values (98, 'Kris Inc', '98205 Kinsman Pass', 98);
insert into hotel (id_hotel, hotel_name, address, id_province) values (99, 'Collier-Runolfsson', '9940 4th Center', 99);
insert into hotel (id_hotel, hotel_name, address, id_province) values (100, 'Kovacek, Schaden and O''Conner', '54 Mitchell Point', 100);
