insert into province_available (province_name, code_province) values ('North Carolina', 1);
insert into province_available (province_name, code_province) values ('Georgia', 2);
insert into province_available (province_name, code_province) values ('Alabama', 3);
insert into province_available (province_name, code_province) values ('Florida', 4);
insert into province_available (province_name, code_province) values ('New Jersey', 5);
insert into province_available (province_name, code_province) values ('California', 6);
insert into province_available (province_name, code_province) values ('California', 7);
insert into province_available (province_name, code_province) values ('Texas', 8);
insert into province_available (province_name, code_province) values ('Montana', 9);
insert into province_available (province_name, code_province) values ('Massachusetts', 10);
insert into province_available (province_name, code_province) values ('Texas', 11);
insert into province_available (province_name, code_province) values ('Minnesota', 12);
insert into province_available (province_name, code_province) values ('New York', 13);
insert into province_available (province_name, code_province) values ('North Carolina', 14);
insert into province_available (province_name, code_province) values ('Ohio', 15);
insert into province_available (province_name, code_province) values ('California', 16);
insert into province_available (province_name, code_province) values ('Alaska', 17);
insert into province_available (province_name, code_province) values ('California', 18);
insert into province_available (province_name, code_province) values ('Delaware', 19);
insert into province_available (province_name, code_province) values ('Pennsylvania', 20);
insert into province_available (province_name, code_province) values ('North Carolina', 21);
insert into province_available (province_name, code_province) values ('Tennessee', 22);
insert into province_available (province_name, code_province) values ('Washington', 23);
insert into province_available (province_name, code_province) values ('Texas', 24);
insert into province_available (province_name, code_province) values ('Indiana', 25);
insert into province_available (province_name, code_province) values ('North Carolina', 26);
insert into province_available (province_name, code_province) values ('Kentucky', 27);
insert into province_available (province_name, code_province) values ('Florida', 28);
insert into province_available (province_name, code_province) values ('Oregon', 29);
insert into province_available (province_name, code_province) values ('Oklahoma', 30);
insert into province_available (province_name, code_province) values ('North Carolina', 31);
insert into province_available (province_name, code_province) values ('Texas', 32);
insert into province_available (province_name, code_province) values ('Texas', 33);
insert into province_available (province_name, code_province) values ('Florida', 34);
insert into province_available (province_name, code_province) values ('California', 35);
insert into province_available (province_name, code_province) values ('Texas', 36);
insert into province_available (province_name, code_province) values ('Florida', 37);
insert into province_available (province_name, code_province) values ('Alaska', 38);
insert into province_available (province_name, code_province) values ('Missouri', 39);
insert into province_available (province_name, code_province) values ('Texas', 40);
insert into province_available (province_name, code_province) values ('North Carolina', 41);
insert into province_available (province_name, code_province) values ('Georgia', 42);
insert into province_available (province_name, code_province) values ('Texas', 43);
insert into province_available (province_name, code_province) values ('Alabama', 44);
insert into province_available (province_name, code_province) values ('West Virginia', 45);
insert into province_available (province_name, code_province) values ('New York', 46);
insert into province_available (province_name, code_province) values ('New York', 47);
insert into province_available (province_name, code_province) values ('Florida', 48);
insert into province_available (province_name, code_province) values ('District of Columbia', 49);
insert into province_available (province_name, code_province) values ('Washington', 50);
insert into province_available (province_name, code_province) values ('California', 51);
insert into province_available (province_name, code_province) values ('California', 52);
insert into province_available (province_name, code_province) values ('New York', 53);
insert into province_available (province_name, code_province) values ('Indiana', 54);
insert into province_available (province_name, code_province) values ('Nevada', 55);
insert into province_available (province_name, code_province) values ('New York', 56);
insert into province_available (province_name, code_province) values ('Kentucky', 57);
insert into province_available (province_name, code_province) values ('Georgia', 58);
insert into province_available (province_name, code_province) values ('California', 59);
insert into province_available (province_name, code_province) values ('South Carolina', 60);
insert into province_available (province_name, code_province) values ('Missouri', 61);
insert into province_available (province_name, code_province) values ('District of Columbia', 62);
insert into province_available (province_name, code_province) values ('California', 63);
insert into province_available (province_name, code_province) values ('District of Columbia', 64);
insert into province_available (province_name, code_province) values ('Louisiana', 65);
insert into province_available (province_name, code_province) values ('Washington', 66);
insert into province_available (province_name, code_province) values ('Washington', 67);
insert into province_available (province_name, code_province) values ('Massachusetts', 68);
insert into province_available (province_name, code_province) values ('Virginia', 69);
insert into province_available (province_name, code_province) values ('California', 70);
insert into province_available (province_name, code_province) values ('Alabama', 71);
insert into province_available (province_name, code_province) values ('Ohio', 72);
insert into province_available (province_name, code_province) values ('North Carolina', 73);
insert into province_available (province_name, code_province) values ('Texas', 74);
insert into province_available (province_name, code_province) values ('Virginia', 75);
insert into province_available (province_name, code_province) values ('Illinois', 76);
insert into province_available (province_name, code_province) values ('Tennessee', 77);
insert into province_available (province_name, code_province) values ('California', 78);
insert into province_available (province_name, code_province) values ('Nebraska', 79);
insert into province_available (province_name, code_province) values ('California', 80);
insert into province_available (province_name, code_province) values ('Michigan', 81);
insert into province_available (province_name, code_province) values ('California', 82);
insert into province_available (province_name, code_province) values ('Oklahoma', 83);
insert into province_available (province_name, code_province) values ('Alabama', 84);
insert into province_available (province_name, code_province) values ('Maryland', 85);
insert into province_available (province_name, code_province) values ('Nevada', 86);
insert into province_available (province_name, code_province) values ('Washington', 87);
insert into province_available (province_name, code_province) values ('New York', 88);
insert into province_available (province_name, code_province) values ('Colorado', 89);
insert into province_available (province_name, code_province) values ('Texas', 90);
insert into province_available (province_name, code_province) values ('Pennsylvania', 91);
insert into province_available (province_name, code_province) values ('North Dakota', 92);
insert into province_available (province_name, code_province) values ('Texas', 93);
insert into province_available (province_name, code_province) values ('Florida', 94);
insert into province_available (province_name, code_province) values ('New York', 95);
insert into province_available (province_name, code_province) values ('Virginia', 96);
insert into province_available (province_name, code_province) values ('Illinois', 97);
insert into province_available (province_name, code_province) values ('New York', 98);
insert into province_available (province_name, code_province) values ('Alabama', 99);
insert into province_available (province_name, code_province) values ('Minnesota', 100);
