insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (77553, 'convallis tortor risus dapibus augue', 1, 1, 1, 1, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (88680, 'leo odio condimentum id luctus', 1, 2, 2, 2, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (96236, 'faucibus accumsan odio curabitur convallis', 1, 3, 3, 3, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (59713, 'odio elementum eu interdum', 1, 4, 4, 4, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (44010, 'non', 2, 5, 5, 5, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (80168, 'pede venenatis', 1, 6, 6, 6, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (98100, 'at velit eu est', 1, 7, 7, 7, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (50376, 'erat', 1, 8, 8, 8, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (58818, 'luctus et ultrices posuere cubilia', 1, 9, 9, 9, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (47369, 'est lacinia', 1, 10, 10, 10, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (52031, 'eu', 1, 11, 11, 11, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (76913, 'non', 1, 12, 12, 12, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (46508, 'rutrum ac lobortis', 2, 13, 13, 13, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (37061, 'nec euismod scelerisque quam', 2, 14, 14, 14, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (2008, 'elementum nullam varius nulla', 1, 15, 15, 15, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (75397, 'vel', 1, 16, 16, 16, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (65658, 'urna', 2, 17, 17, 17, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (38592, 'sit amet', 1, 18, 18, 18, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (79278, 'ipsum primis in', 1, 19, 19, 19, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (62406, 'vitae nisl aenean lectus', 1, 20, 20, 20, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (34963, 'amet', 1, 21, 21, 21, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (91555, 'nisi nam ultrices', 1, 22, 22, 22, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (12080, 'nisi eu orci mauris', 2, 23, 23, 23, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (88878, 'velit nec nisi vulputate', 1, 24, 24, 24, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (89242, 'augue quam', 1, 25, 25, 25, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (14242, 'id nisl venenatis lacinia aenean', 1, 26, 26, 26, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (56539, 'elit sodales', 2, 27, 27, 27, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (76471, 'parturient montes nascetur ridiculus', 1, 28, 28, 28, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (96219, 'eu', 2, 29, 29, 29, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (82919, 'enim blandit', 1, 30, 30, 30, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (54742, 'convallis morbi', 1, 31, 31, 31, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (98998, 'nunc vestibulum ante ipsum primis', 1, 32, 32, 32, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (78199, 'sem', 2, 33, 33, 33, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (60587, 'massa id lobortis', 1, 34, 34, 34, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (61843, 'phasellus', 1, 35, 35, 35, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (99068, 'suspendisse accumsan tortor', 2, 36, 36, 36, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (64089, 'et', 1, 37, 37, 37, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (46127, 'ligula suspendisse ornare consequat', 1, 38, 38, 38, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (49637, 'nulla quisque arcu', 1, 39, 39, 39, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (23724, 'bibendum morbi', 2, 40, 40, 40, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (58105, 'nulla tellus in sagittis dui', 1, 41, 41, 41, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (25925, 'dolor quis odio', 1, 42, 42, 42, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (46686, 'iaculis diam erat', 1, 43, 43, 43, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (4030, 'orci luctus et ultrices posuere', 2, 44, 44, 44, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (4781, 'sem', 1, 45, 45, 45, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (76509, 'volutpat eleifend donec ut dolor', 1, 46, 46, 46, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (8096, 'mauris sit amet eros suspendisse', 1, 47, 47, 47, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (7925, 'lorem', 1, 48, 48, 48, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (33342, 'mauris', 1, 49, 49, 49, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (4657, 'donec', 2, 50, 50, 50, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (90807, 'fusce lacus', 1, 51, 51, 51, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (44725, 'faucibus', 1, 52, 52, 52, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (52587, 'duis ac nibh', 1, 53, 53, 53, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (23363, 'imperdiet nullam orci pede', 1, 54, 54, 54, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (75440, 'id lobortis convallis', 1, 55, 55, 55, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (59369, 'praesent id massa', 2, 56, 56, 56, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (84690, 'vestibulum proin eu mi', 1, 57, 57, 57, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (26484, 'in hac habitasse platea', 2, 58, 58, 58, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (79610, 'nulla', 2, 59, 59, 59, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (99895, 'volutpat erat quisque erat', 2, 60, 60, 60, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (15400, 'nascetur ridiculus mus vivamus', 1, 61, 61, 61, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (8069, 'at', 2, 62, 62, 62, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (42349, 'tempus vivamus in felis', 1, 63, 63, 63, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (54585, 'venenatis tristique', 2, 64, 64, 64, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (48383, 'phasellus', 1, 65, 65, 65, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (26962, 'vulputate nonummy maecenas tincidunt', 1, 66, 66, 66, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (78570, 'eu sapien cursus', 1, 67, 67, 67, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (22154, 'iaculis congue vivamus metus arcu', 1, 68, 68, 68, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (19683, 'habitasse', 2, 69, 69, 69, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (40987, 'cras mi pede', 2, 70, 70, 70, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (45961, 'nullam varius nulla facilisi cras', 2, 71, 71, 71, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (37743, 'viverra dapibus nulla', 2, 72, 72, 72, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (68871, 'congue etiam justo', 2, 73, 73, 73, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (5262, 'hac', 1, 74, 74, 74, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (58052, 'nulla tellus in sagittis', 2, 75, 75, 75, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (94980, 'lobortis ligula sit', 1, 76, 76, 76, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (83329, 'in imperdiet et commodo vulputate', 2, 77, 77, 77, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (5244, 'nec molestie sed justo pellentesque', 1, 78, 78, 78, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (51535, 'consequat metus', 2, 79, 79, 79, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (43263, 'dolor', 1, 80, 80, 80, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (3017, 'tristique tortor eu pede', 2, 81, 81, 81, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (3425, 'in consequat', 1, 82, 82, 82, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (24363, 'leo pellentesque ultrices', 1, 83, 83, 83, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (88039, 'non quam nec', 1, 84, 84, 84, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (77862, 'blandit', 1, 85, 85, 85, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (91902, 'in faucibus', 2, 86, 86, 86, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (9388, 'duis mattis egestas', 2, 87, 87, 87, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (33240, 'tristique est et', 1, 88, 88, 88, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (14526, 'vulputate', 2, 89, 89, 89, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (73662, 'imperdiet sapien urna pretium nisl', 2, 90, 90, 90, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (65535, 'luctus', 2, 91, 91, 91, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (65501, 'egestas metus', 1, 92, 92, 92, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (80060, 'morbi vestibulum', 1, 93, 93, 93, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (53563, 'volutpat quam pede', 1, 94, 94, 94, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (55859, 'eget', 1, 95, 95, 95, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (83615, 'metus sapien ut nunc vestibulum', 2, 96, 96, 96, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (50137, 'volutpat eleifend donec', 1, 97, 97, 97, true);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (58762, 'ultrices posuere', 1, 98, 98, 98, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (34310, 'nibh fusce lacus', 2, 99, 99, 99, false);
insert into room (number, room_type, capacity_room, id_promotion, id_reservation, id_features, id_hotel) values (99700, 'curae nulla', 1, 100, 100, 100, false);
