
insert into service (service_name, description, price, reduction) values ('concierge service', 'Beautiful views', 298.01, 347.72);
insert into service (service_name, description, price, reduction) values ('bar service', 'Excellent customer service', 685.37, 478.81);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Convenient location', 282.65, 57.12);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Top-notch amenities', 181.99, 64.6);
insert into service (service_name, description, price, reduction) values ('bar service', 'Excellent customer service', 807.46, 341.25);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Excellent customer service', 502.65, 253.71);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Top-notch amenities', 278.28, 835.95);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Excellent customer service', 801.64, 629.12);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Convenient location', 107.36, 898.33);
insert into service (service_name, description, price, reduction) values ('room service', 'Convenient location', 562.72, 658.09);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Luxurious accommodations', 489.20, 327.15);
insert into service (service_name, description, price, reduction) values ('bar service', 'Exquisite dining options', 615.80, 182.47);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Personalized assistance', 724.56, 543.90);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Elegant ambiance', 293.75, 129.78);
insert into service (service_name, description, price, reduction) values ('room service', '24/7 availability', 421.08, 265.43);
insert into service (service_name, description, price, reduction) values ('bar service', 'Crafted cocktails', 173.89, 88.65);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Cultural experiences', 630.12, 421.05);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Fine wine selection', 586.40, 296.71);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Exclusive event planning', 458.91, 198.22);
insert into service (service_name, description, price, reduction) values ('room service', 'Gourmet room dining', 329.50, 76.99);
insert into service (service_name, description, price, reduction) values ('bar service', 'Live entertainment', 258.32, 112.67);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Private spa access', 569.75, 438.90);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Spectacular views', 642.89, 367.25);
insert into service (service_name, description, price, reduction) values ('bar service', 'Handcrafted cuisine', 376.21, 187.32);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Local area tours', 192.78, 98.43);
insert into service (service_name, description, price, reduction) values ('room service', 'Customizable menu', 543.10, 265.17);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Artisanal beverages', 389.23, 172.89);
insert into service (service_name, description, price, reduction) values ('bar service', 'Signature cocktails', 725.42, 341.76);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Private beach access', 265.17, 129.64);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Gastronomic delights', 489.76, 264.98);
insert into service (service_name, description, price, reduction) values ('bar service', 'Live music events', 312.58, 156.32);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Fitness and wellness', 586.32, 372.89);
insert into service (service_name, description, price, reduction) values ('room service', 'In-room massage', 427.50, 215.98);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Artfully presented dishes', 349.28, 187.43);
insert into service (service_name, description, price, reduction) values ('bar service', 'Lively evening atmosphere', 198.43, 89.67);
insert into service (service_name, description, price, reduction) values ('concierge service', 'Personal shopping assistance', 615.99, 327.12);
insert into service (service_name, description, price, reduction) values ('waiter service', 'Culinary journey', 482.73, 259.18);
insert into service (service_name, description, price, reduction) values ('bar service', 'Chic cocktail lounge', 527.12, 176.39);
insert into service (service_name, description, price, reduction) values ('concierge service', 'VIP event access', 293.18, 128.65);
insert into service (service_name, description, price, reduction) values ('room service', 'Private dining experiences', 371.25, 187.32);
