insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 1, 1, true, true, 1);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 6, 2, false, true, 2);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 3, 6, true, false, 3);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 7,9, true, true, 4);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 5, 5, true, false, 5);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 6, 6, true, false, 6);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 5, 4, true, true, 7);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 8, 8, false, false, 8);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 9, 9, true, false, 9);
insert into status_client ( status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values ( 1, 10, false, true, 10);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (1, 1, true, true, 2);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (6, 2, false, true, 3);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (3, 6, true, false, 4);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (7, 9, true, true, 5);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (5, 5, true, false, 6);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (6, 6, true, false, 7);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (5, 4, true, true, 8);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (8, 8, false, false, 9);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (9, 9, true, false, 10);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (1, 10, false, true, 11);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (3, 8, true, false, 12);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (5, 6, true, true, 13);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (7, 4, false, false, 14);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (2, 9, false, true, 15);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (4, 3, true, false, 16);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (6, 2, false, true, 17);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (8, 7, true, false, 18);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (9, 5, false, false, 19);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (1, 10, true, true, 20);
insert into status_client (status_arrived, status_missing, in_fidelity, in_blacklist, id_client) values (4, 8, false, true, 21);

